version: "3.7"

services:
  flask:
    build: ./flask
    container_name: flask_app
    ports:
      - "8000:8000"

  nginx: 
    build: ./react-flask-graph
    container_name: nginx
    ports:
      - "8080:8080"

  # neo4j: 
  #   build: ./neo4j
  #   container_name: neo4j
  #   ports:
  #     - "7474:7474"
  #     - "7687:7687"
  #   environment:
  #     - NEO4J_AUTH=neo4j/test 
      
    # links:
    #   - flask